### PR TITLE
Updated Utils with new functionality 

### PR DESCRIPTION
**Pull request by ElPsyKurisu**
Changed the Keithley 6221 instrument to support duty cycles, pulse duration and more.

Overwrote get_number_and_suffix with regex version

Added Util functionality and added null values for mappers

### CODE REVIEW

**Review by eparsonnet93 — CHANGES_REQUESTED** [review]
You deleted the function `set_output_sin` in `keithley6221/core`. This isn't a great practice because if someone has existing code running that uses that function, it will break. An easy solution to this is to keep `set_output_sin` as a function but redefine it such that it points to your new function `set_output_waveform` with kwarg `waveform='sin'`.  

Then, you should add a deprecation warning into `set_output_sin`: Here is an example of how to do that:

```
import warnings
def set_output_sin(...)
    ...
    warnings.showwarning("set_output_sin is deprecated. Use set_output_waveform instead.", DeprecationWarning, '', 0)
```


also in utils/core can you please remove `get_number_and_suffix_regex` from `__all__`? or is there a reason you have it there?

otherwise looks good!!

**Comment by ElPsyKurisu** [comment]
Gotcha, i had it in there because I wasn't sure if I should overwrite it or not, but fixed that now

**Comment by ElPsyKurisu** [comment]
Fixed both requests

**Review by eparsonnet93 — APPROVED** [review]
There is still a problem with `set_output_sin`. The way it is written now, the user is unable to change the compliance since `set_output_waveform` is hard-coded with a compliance of 1.1. 

I'll approve your merge and fix it myself. Just FYI

**Pull request merged**
